kind: pipeline
name: default

steps:
- name: test
  image: python
  commands:
  - pip install 
  - pytest
  
- name: docker  
  image: plugins/docker
  settings:
    # registry: docker.io
    repo: pavansa/lakaka
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags: 
      - latest
